### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by TrevorBasinger** [unicorn-standard/starter-kit#4]
Hey, this is probably a dumb issue, but I wanted to make you aware of it so other people don't have the same problem.

I'm using nodejs v5.0 and I get the error below. However, 0.12.7 works fine. Looks like I need a harmony flag set somewhere. I'm just not sure the best way to work that into this configuration. Thoughts?

```
/Users/Trevor/starter-kit/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import del from "del";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Trevor/.nvm/versions/node/v5.0.0/bin/node" "/Users/Trevor/.nvm/versions/node/v5.0.0/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! @0.1.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.1.0 start script 'gulp serve'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Trevor/starter-kit/npm-debug.log
```

**Comment by rclanan** [comment]
Maybe update your version of NPM? I just downloaded and tried this as well.

Mac OS X version: 10.11 (Darwin version 15.0.0)
Node version: 5.0.0
NPM version: 3.3.12

Everything appears to be running fine running on those versions.

**Comment by TrevorBasinger** [comment]
Ah, thanks! That's what it was.

**Comment by rclanan** [comment]
No problem! Glad it worked for you.
